In [5]:
import numpy as np
truemodel = {}
num_resources = 3;

truemodel["As"] = np.zeros((num_resources, 2, 2), dtype=np.float_)
p_T = 0.1
p_F = 0.3
for i in range(num_resources):
    truemodel["As"][i] = np.transpose([[1-p_T, p_T], [p_F, 1-p_F]])

print(truemodel["As"])
truemodel["As"][:,1,0]

[[[0.9 0.3]
  [0.1 0.7]]

 [[0.9 0.3]
  [0.1 0.7]]

 [[0.9 0.3]
  [0.1 0.7]]]


array([0.1, 0.1, 0.1])