In [50]:
import numpy as np
truemodel = {}
num_resources = 3;

truemodel["As"] = np.zeros((num_resources, 2, 2), dtype=np.float_)
p_T = 0.1
p_F = 0.3
for i in range(num_resources):
    truemodel["As"][i] = np.transpose([[1-p_T, p_T], [p_F, 1-p_F]])

observation_sequence_lengths = np.full((50,30), 100, dtype=np.int)
temp = np.sum(observation_sequence_lengths, axis = 1, keepdims = True)
observation_sequence_lengths/temp

array([[0.03333333, 0.03333333, 0.03333333, ..., 0.03333333, 0.03333333,
        0.03333333],
       [0.03333333, 0.03333333, 0.03333333, ..., 0.03333333, 0.03333333,
        0.03333333],
       [0.03333333, 0.03333333, 0.03333333, ..., 0.03333333, 0.03333333,
        0.03333333],
       ...,
       [0.03333333, 0.03333333, 0.03333333, ..., 0.03333333, 0.03333333,
        0.03333333],
       [0.03333333, 0.03333333, 0.03333333, ..., 0.03333333, 0.03333333,
        0.03333333],
       [0.03333333, 0.03333333, 0.03333333, ..., 0.03333333, 0.03333333,
        0.03333333]])

In [42]:
trans_prior = np.tile(np.transpose([[20, 4], [1, 20]]), (num_resources, 1)).reshape((num_resources,2,2))
trans_prior = np.transpose([[20, 4], [1, 20]])
print(trans_prior)
np.sum(trans_prior,1)

[[20  1]
 [ 4 20]]


array([21, 24])

In [45]:
a = np.tile([[5], [0.5]], (1, num_resources))
a= np.array([[100], [1]])
a = np.random.gamma(alphavec, 1)
a

TypeError: gamma() got an unexpected keyword argument 'axis'