In [51]:
import numpy as np
truemodel = {}
num_resources = 3;
num_subparts = 3;

truemodel["As"] = np.zeros((num_resources, 2, 2), dtype=np.float_)
p_T = 0.1
p_F = 0.3
for i in range(num_resources):
    truemodel["As"][i] = np.transpose([[1-p_T, p_T], [p_F, 1-p_F]])

observation_sequence_lengths = np.full((50,30), 100, dtype=np.int)
temp = np.sum(observation_sequence_lengths, axis = 1, keepdims = True)
observation_sequence_lengths/temp

array([[0.03333333, 0.03333333, 0.03333333, ..., 0.03333333, 0.03333333,
        0.03333333],
       [0.03333333, 0.03333333, 0.03333333, ..., 0.03333333, 0.03333333,
        0.03333333],
       [0.03333333, 0.03333333, 0.03333333, ..., 0.03333333, 0.03333333,
        0.03333333],
       ...,
       [0.03333333, 0.03333333, 0.03333333, ..., 0.03333333, 0.03333333,
        0.03333333],
       [0.03333333, 0.03333333, 0.03333333, ..., 0.03333333, 0.03333333,
        0.03333333],
       [0.03333333, 0.03333333, 0.03333333, ..., 0.03333333, 0.03333333,
        0.03333333]])

In [60]:
trans_prior = np.tile(np.transpose([[20, 4], [1, 20]]), (num_resources, 1)).reshape((num_resources,2,2))
#trans_prior = np.transpose([[20, 4], [1, 20]])
print(trans_prior)
print(trans_prior[:,0,1])
np.sum(trans_prior,1)

[[[20  1]
  [ 4 20]]

 [[20  1]
  [ 4 20]]

 [[20  1]
  [ 4 20]]]
[1 1 1]


array([[24, 21],
       [24, 21],
       [24, 21]])

In [53]:
a = np.tile([[5], [0.5]], (1, num_resources))
a= np.array([[100], [1]])
a = np.random.gamma(alphavec, 1)
a

NameError: name 'alphavec' is not defined

In [63]:
given_notknow = np.tile([[5], [0.5]], (1, num_subparts))
given_know = np.tile([[0.6], [6]], (1, num_subparts))
print(given_notknow)
print(given_notknow[1,:])
emissions = np.stack((np.transpose(given_notknow.reshape((2, num_subparts))), np.transpose(given_know.reshape((2, num_subparts)))), axis=1)
emissions[-1]

[[5.  5.  5. ]
 [0.5 0.5 0.5]]
[0.5 0.5 0.5]


array([[5. , 0.5],
       [0.6, 6. ]])

In [66]:
arr = [1,2,3,4]
arr[0]

1